CREATE TABLE IF NOT EXISTS `ryby` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `gatunek` VARCHAR(30) NOT NULL,
  `typ` VARCHAR(30) NOT NULL,
  `poczatek_okresu` INT,
  `koniec_okresu` INT
);

INSERT INTO Ryby (gatunek, typ, poczatek_okresu, koniec_okresu) VALUES
('Szczupak', 'jeziorna drapieżna', 3, 24),
('Sandacz', 'jeziorna drapieżna', 15, 26),
('Sum', 'rzeczna drapieżna', NULL, NULL),
('Okoń', 'jeziorna drapieżna', NULL, NULL),
('Węgorz', 'rzeczna drapieżna', 49, 10),
('Pstrąg potokowy', 'rzeczna drapieżna', 15, 26),
('Troć wędrowna', 'morska drapieżna', 15, 26),
('Łosoś atlantycki', 'rzeczna drapieżna', 11, 29),
('Karaś', 'jeziorna niedrapieżna', NULL, NULL),
('Karp', 'jeziorna niedrapieżna', NULL, NULL),
('Lin', 'jeziorna niedrapieżna', NULL, NULL),
('Leszcz', 'jeziorna niedrapieżna', NULL, NULL),
('Płoć', 'jeziorna niedrapieżna', NULL, NULL),
('Wzdręga', 'jeziorna niedrapieżna', NULL, NULL),
('Szczupak karłowaty', 'jeziorna drapieżna', 3, 24),
('Miętus', 'jeziorna drapieżna', 15, 26),
('Kiełb', 'jeziorna niedrapieżna', NULL, NULL),
('Głowacz', 'rzeczna drapieżna', NULL, NULL),
('Okoniec', 'jeziorna drapieżna', NULL, NULL),
('Sandacz południowy', 'jeziorna drapieżna', 15, 26),
('Sielawa', 'rzeczna drapieżna', 11, 20),
('Kleń', 'rzeczna drapieżna', NULL, NULL),
('Jaz', 'rzeczna drapieżna', NULL, NULL),
('Mulet', 'morska niedrapieżna', NULL, NULL),
('Szczupak błotny', 'jeziorna drapieżna', 3, 24),
('Pstrąg tęczowy', 'jeziorna drapieżna', 15, 26),
('Lin pajdowany', 'jeziorna niedrapieżna', NULL, NULL),
('Karaś srebrzysty', 'jeziorna niedrapieżna', NULL, NULL),
('Amur', 'jeziorna niedrapieżna', NULL, NULL),
('Karp koi', 'jeziorna niedrapieżna', NULL, NULL),
('Okonica', 'jeziorna drapieżna', NULL, NULL),
('Boleń', 'jeziorna drapieżna', 15, 25),
('Perła rzeczna', 'rzeczna niedrapieżna', NULL, NULL),
('Jaz karpacki', 'rzeczna drapieżna', NULL, NULL),
('Suma karpacki', 'rzeczna drapieżna', 3, 22),
('Pstrąg źródlany', 'rzeczna drapieżna', 12, 25),
('Troć potokowa', 'rzeczna drapieżna', 15, 26),
('Leszcz srokaty', 'jeziorna niedrapieżna', NULL, NULL),
('Kiełb śródlądowy', 'jeziorna niedrapieżna', NULL, NULL),
('Lin zwyczajny', 'jeziorna niedrapieżna', NULL, NULL),
('Szczupak rzeczny', 'rzeczna drapieżna', 3, 24),
('Okoniec karpacki', 'jeziorna drapieżna', NULL, NULL),
('Płoć śródlądowa', 'jeziorna niedrapieżna', NULL, NULL),
('Wzdręga rzeczna', 'jeziorna niedrapieżna', NULL, NULL),
('Karaś pospolity', 'jeziorna niedrapieżna', NULL, NULL),
('Karp marmurkowy', 'jeziorna niedrapieżna', NULL, NULL),
('Miętus rzeczny', 'rzeczna drapieżna', 10, 26),
('Sielawa rzeczna', 'rzeczna drapieżna', 11, 20),
('Sandacz jeziorowy', 'jeziorna drapieżna', 15, 26),
('Boleń', 'jeziorna drapieżna', 15, 25);
